### PR TITLE
make component accept custom className

### PR DESCRIPTION
**Pull request by FezVrasta**
This can be useful. In my case, I'd need a bit of padding on the element to make a shadow avoid from being clipped.

### CODE REVIEW

**Comment by FezVrasta** [comment]
Also, I was wondering why you need two `overflow: hidden` wrappers. I guess one should be enough?

**Comment by Macil** [comment]
Is there a reason that putting a class on a div around or inside the SmoothCollapse component can't solve your problem? I'm aware that may create some apparently unnecessary wrapper divs, but I feel there are benefits to SmoothCollapse to having that separation. If it can be avoided, I'd rather not have the API expose the fact that the SmoothCollapse component is currently made out of two divs, or allow the component's own elements to be directly re-styled, which restricts the type of changes that can be made to SmoothCollapse without breaking applications.

**Comment by FezVrasta** [comment]
I have two cards one above the other.

```
<Card />
<Collapse>
 <Card />
</Collapse>
```

They have the same width, and they have a `box-shadow` around.
The one wrapped by `Collapse` has not shadow because of `oveflow: hidden`.

If I want to fix it, I need to add a negative margin (`-5px`) and a padding (`5px`) so that the `Collapse` component is shifted a bit to the outside.
I can't just add an inner wrapper because it wouldn't make the trick (the `overflow: hidden` would hide the shadow anyway).

By the way, it's a so small addition that has only advantages, I would really like to get it added.
Right now I just published the fork on `react-smooth-collapse-customizable`, but I'd like to use the official version.

**Comment by Macil** [comment]
Couldn't that be solved with some wrapper divs?

```
<Card />
<div style={{margin: '-5px'}}>
  <Collapse>
    <div style={{padding: '5px'}}>
      <Card />
    </div>
  </Collapse>
</div>
```

I'm going to close this for the reasons mentioned above, but if you find that the problem can't be solved by a solution like this then please let us know!

**Pull request closed without merging**
